"""2D product composition experiments

Compute metrics from samples generated by the 'train_script_product' script
"""
from argparse import ArgumentParser
import pickle
from pathlib import Path


def main():
    args = parse_args()
    for sample_file in args.samples_path.glob("samples*.p"):
        samples = pickle.load(open(sample_file, "rb"))
        for name, sample in samples.items():
            print(name)


def parse_args():
    parser = ArgumentParser(prog="compute_metrics_product")
    parser.add_argument("--samples_path", default=None, type=Path)
    return parser.parse_args()


if __name__ == "__main__":
    main()
